### ISSUE TITLE
Cannot pop to root unless initial route pathname is "/"

### ISSUE THREAD

**Issue by kyle-ssg** [ajsmth/earhart#3]
Loving this so far, found a slight gotcha with this:

Popping to the root is not possible unless the initial <Route> path is "/"
```
    const history = useHistory();
    history.go(-history.entries.length)
```

Digging through the code, I think this is due to how the memoryHistory is behaves by default. It looks like given the following router treats the initial path is always set to "/"

With the following Navigator the memoryHistory is created incorrectly

```
 <Navigator initialIndex={0}>
                    <Stack>
                        <Route gestureEnabled path="/1">
                            <Header titleColor="#ffffff" largeTitle titale="Test"
                              backgroundColor="transparent"/>
                            <Home />
                        </Route>
                        <Route gestureEnabled path="/2">
                            <Header titleColor="#ffffff" largeTitle title="Test2"
                              backgroundColor="transparent"/>
                            <Home />
                        </Route>
                        <Route gestureEnabled path="/3">
                            <Header titleColor="#ffffff" largeTitle title="Test3"
                              backgroundColor="transparent"/>
                            <Home />
                        </Route>
                    </Stack>
</Navigator>
```

![image](https://user-images.githubusercontent.com/8608314/77853730-99c8b480-71dd-11ea-9779-b5713b7ea93a.png)

However given the following markup the router behaves fine
```
 <Navigator initialIndex={0}>
                    <Stack>
                        <Route gestureEnabled path="/">
                            <Header titleColor="#ffffff" largeTitle titale="Test"
                              backgroundColor="transparent"/>
                            <Home />
                        </Route>
                        <Route gestureEnabled path="/2">
                            <Header titleColor="#ffffff" largeTitle title="Test2"
                              backgroundColor="transparent"/>
                            <Home />
                        </Route>
                        <Route gestureEnabled path="/3">
                            <Header titleColor="#ffffff" largeTitle title="Test3"
                              backgroundColor="transparent"/>
                            <Home />
                        </Route>
                    </Stack>
</Navigator>
```

**Comment by ajsmth** [comment]
hey there - thanks for doing all this. i'm not sure i follow, are you trying to push to a root path that is not "/"? have you tried adding the initialEntries to `<Router />` ?

**Comment by kyle-ssg** [comment]
Kind of, I'm trying to just pop to the initial route, but it seems to think that the pathname is "/" where it's actually "/1"


![image](https://user-images.githubusercontent.com/8608314/77854147-62a7d280-71e0-11ea-8a1b-4ad7f4425c59.png)


This means that history.go(-history.entries.length) or going to "/1" will not work

**Comment by kyle-ssg** [comment]
Right yep if I do the following it works 

```
            <Router initialEntries={["/1"]}>
```

**Comment by ajsmth** [comment]
ah yes i think i understand now - `<Router initialEntries={['/1']} />` should fix this in this case. 

the routes themselves don't push or replace location on mount, only links, gestures, and navigate()

**Comment by ajsmth** [comment]
@kyle-ssg good to close this or did you have any suggestions here?

**Comment by kyle-ssg** [comment]
@ajsmth I think this is one for documenting, not sure if maybe the initialEntries should be a required prop too. I'm playing around with the lib as I'm getting free time, making a WhatsApp clone to test it all out but so far I feel like I can achieve more using this than react-native-navigation.

**Comment by kyle-ssg** [comment]
Will close for now.
