### ISSUE TITLE
History continues to climb even when going back

### ISSUE THREAD

**Issue by kyle-ssg** [ajsmth/earhart#4]
This is best described through the following gif, using the history.index prop, I noticed that the number continues to increase when navigating back through a stack

<img src="https://recordit.co/8WAi9HpYfe.gif"/>

**Comment by ajsmth** [comment]
ah thanks, I know whats going on here. theres a reason its a push instead of go(-1) but i can think of a workaround for this. thanks for finding this!

**Comment by ajsmth** [comment]
this one is a little tricky as i'm not sure what the best behaviour should be.
in this case it's definitely a pop, but i can think of other cases where a pop would result in navigating to a different screen depending on the app's history. 

i can think of some solutions but they might be more difficult to use / confusing. i'll keep this open until i've decided.

 curious as to the downside of having the stack

**Comment by kyle-ssg** [comment]
Hmm yeah potentially there isn't one, I haven't realised the full usage of history.entires yet, I'd imagine this affects goBack and if you wanted to show a non-native back button based on where you are in the stack

**Comment by ajsmth** [comment]
i would use a link in that scenario. in general i’ve found using paths is more predictable than going through the history stack

**Comment by kyle-ssg** [comment]
I'm presuming this does not mean that there's any form of leakage? The reason why I mention this is because of the following from the readme "this library tends to keep views alive instead of unmounting them." - Hopefully this does not mean that in my above example several of each component are mounted. 

I guess regardless of this I'm curious to see if this approach has some form of cpu bottleneck when redux state changes force state changes on many hidden routes.

**Comment by ajsmth** [comment]
i think the readme might be a bit misleading then - it keeps sibling views alive. in this example its pushing and popping the view as you would expect. 

large updates are definitely a concern, but i would think there are ways around preventing updates using something like the `useFocus` flag depending on your use case. i'm interested as well in this.

**Comment by kyle-ssg** [comment]
I'll close this as there's nothing immediately actionable I think!
